### ISSUE TITLE
Баг с отображением текстур

### ISSUE THREAD

**Issue by Thorgathis** [IBit-mc-server/ResourcePack#3]
![изображение](https://user-images.githubusercontent.com/92544658/235229158-c8d1b48c-2b69-4595-bc53-bcd28e66fc57.png)
![изображение](https://user-images.githubusercontent.com/92544658/235229428-aada63ba-c7c1-4309-bd28-8549bb1634e8.png)
![изображение](https://user-images.githubusercontent.com/92544658/235227085-9c4c981b-0b48-4a77-8352-e516668c445f.png)

@spytaspund

**Comment by spytaspund** [comment]
После слияния основной и ветки моего форка всё должно работать отлично.
